// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FPGA_Acc_conv2d_tile4_Pipeline_VITIS_LOOP_369_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln369,
        TM_MIN,
        InterSubBeta_cast,
        local_beta_buffer_0,
        local_beta_buffer_0_ap_vld,
        bias_buffer_address0,
        bias_buffer_ce0,
        bias_buffer_q0,
        local_beta_buffer_1,
        local_beta_buffer_1_ap_vld,
        local_beta_buffer_2,
        local_beta_buffer_2_ap_vld,
        local_beta_buffer_3,
        local_beta_buffer_3_ap_vld,
        local_beta_buffer_4,
        local_beta_buffer_4_ap_vld,
        local_beta_buffer_5,
        local_beta_buffer_5_ap_vld,
        local_beta_buffer_6,
        local_beta_buffer_6_ap_vld,
        local_beta_buffer_7,
        local_beta_buffer_7_ap_vld,
        local_beta_buffer_8,
        local_beta_buffer_8_ap_vld,
        local_beta_buffer_9,
        local_beta_buffer_9_ap_vld,
        local_beta_buffer_10,
        local_beta_buffer_10_ap_vld,
        local_beta_buffer_11,
        local_beta_buffer_11_ap_vld,
        local_beta_buffer_12,
        local_beta_buffer_12_ap_vld,
        local_beta_buffer_13,
        local_beta_buffer_13_ap_vld,
        local_beta_buffer_14,
        local_beta_buffer_14_ap_vld,
        local_beta_buffer_15,
        local_beta_buffer_15_ap_vld,
        local_beta_buffer_16,
        local_beta_buffer_16_ap_vld,
        local_beta_buffer_17,
        local_beta_buffer_17_ap_vld,
        local_beta_buffer_18,
        local_beta_buffer_18_ap_vld,
        local_beta_buffer_19,
        local_beta_buffer_19_ap_vld,
        local_beta_buffer_20,
        local_beta_buffer_20_ap_vld,
        local_beta_buffer_21,
        local_beta_buffer_21_ap_vld,
        local_beta_buffer_22,
        local_beta_buffer_22_ap_vld,
        local_beta_buffer_23,
        local_beta_buffer_23_ap_vld,
        local_beta_buffer_24,
        local_beta_buffer_24_ap_vld,
        local_beta_buffer_25,
        local_beta_buffer_25_ap_vld,
        local_beta_buffer_26,
        local_beta_buffer_26_ap_vld,
        local_beta_buffer_27,
        local_beta_buffer_27_ap_vld,
        local_beta_buffer_28,
        local_beta_buffer_28_ap_vld,
        local_beta_buffer_29,
        local_beta_buffer_29_ap_vld,
        local_beta_buffer_30,
        local_beta_buffer_30_ap_vld,
        local_beta_buffer_31,
        local_beta_buffer_31_ap_vld,
        local_beta_buffer_32,
        local_beta_buffer_32_ap_vld,
        local_beta_buffer_33,
        local_beta_buffer_33_ap_vld,
        local_beta_buffer_34,
        local_beta_buffer_34_ap_vld,
        local_beta_buffer_35,
        local_beta_buffer_35_ap_vld,
        local_beta_buffer_36,
        local_beta_buffer_36_ap_vld,
        local_beta_buffer_37,
        local_beta_buffer_37_ap_vld,
        local_beta_buffer_38,
        local_beta_buffer_38_ap_vld,
        local_beta_buffer_39,
        local_beta_buffer_39_ap_vld,
        local_beta_buffer_40,
        local_beta_buffer_40_ap_vld,
        local_beta_buffer_41,
        local_beta_buffer_41_ap_vld,
        local_beta_buffer_42,
        local_beta_buffer_42_ap_vld,
        local_beta_buffer_43,
        local_beta_buffer_43_ap_vld,
        local_beta_buffer_44,
        local_beta_buffer_44_ap_vld,
        local_beta_buffer_45,
        local_beta_buffer_45_ap_vld,
        local_beta_buffer_46,
        local_beta_buffer_46_ap_vld,
        local_beta_buffer_47,
        local_beta_buffer_47_ap_vld,
        local_beta_buffer_48,
        local_beta_buffer_48_ap_vld,
        local_beta_buffer_49,
        local_beta_buffer_49_ap_vld,
        local_beta_buffer_50,
        local_beta_buffer_50_ap_vld,
        local_beta_buffer_51,
        local_beta_buffer_51_ap_vld,
        local_beta_buffer_52,
        local_beta_buffer_52_ap_vld,
        local_beta_buffer_53,
        local_beta_buffer_53_ap_vld,
        local_beta_buffer_54,
        local_beta_buffer_54_ap_vld,
        local_beta_buffer_55,
        local_beta_buffer_55_ap_vld,
        local_beta_buffer_56,
        local_beta_buffer_56_ap_vld,
        local_beta_buffer_57,
        local_beta_buffer_57_ap_vld,
        local_beta_buffer_58,
        local_beta_buffer_58_ap_vld,
        local_beta_buffer_59,
        local_beta_buffer_59_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sext_ln369;
input  [31:0] TM_MIN;
input  [4:0] InterSubBeta_cast;
output  [31:0] local_beta_buffer_0;
output   local_beta_buffer_0_ap_vld;
output  [9:0] bias_buffer_address0;
output   bias_buffer_ce0;
input  [15:0] bias_buffer_q0;
output  [31:0] local_beta_buffer_1;
output   local_beta_buffer_1_ap_vld;
output  [31:0] local_beta_buffer_2;
output   local_beta_buffer_2_ap_vld;
output  [31:0] local_beta_buffer_3;
output   local_beta_buffer_3_ap_vld;
output  [31:0] local_beta_buffer_4;
output   local_beta_buffer_4_ap_vld;
output  [31:0] local_beta_buffer_5;
output   local_beta_buffer_5_ap_vld;
output  [31:0] local_beta_buffer_6;
output   local_beta_buffer_6_ap_vld;
output  [31:0] local_beta_buffer_7;
output   local_beta_buffer_7_ap_vld;
output  [31:0] local_beta_buffer_8;
output   local_beta_buffer_8_ap_vld;
output  [31:0] local_beta_buffer_9;
output   local_beta_buffer_9_ap_vld;
output  [31:0] local_beta_buffer_10;
output   local_beta_buffer_10_ap_vld;
output  [31:0] local_beta_buffer_11;
output   local_beta_buffer_11_ap_vld;
output  [31:0] local_beta_buffer_12;
output   local_beta_buffer_12_ap_vld;
output  [31:0] local_beta_buffer_13;
output   local_beta_buffer_13_ap_vld;
output  [31:0] local_beta_buffer_14;
output   local_beta_buffer_14_ap_vld;
output  [31:0] local_beta_buffer_15;
output   local_beta_buffer_15_ap_vld;
output  [31:0] local_beta_buffer_16;
output   local_beta_buffer_16_ap_vld;
output  [31:0] local_beta_buffer_17;
output   local_beta_buffer_17_ap_vld;
output  [31:0] local_beta_buffer_18;
output   local_beta_buffer_18_ap_vld;
output  [31:0] local_beta_buffer_19;
output   local_beta_buffer_19_ap_vld;
output  [31:0] local_beta_buffer_20;
output   local_beta_buffer_20_ap_vld;
output  [31:0] local_beta_buffer_21;
output   local_beta_buffer_21_ap_vld;
output  [31:0] local_beta_buffer_22;
output   local_beta_buffer_22_ap_vld;
output  [31:0] local_beta_buffer_23;
output   local_beta_buffer_23_ap_vld;
output  [31:0] local_beta_buffer_24;
output   local_beta_buffer_24_ap_vld;
output  [31:0] local_beta_buffer_25;
output   local_beta_buffer_25_ap_vld;
output  [31:0] local_beta_buffer_26;
output   local_beta_buffer_26_ap_vld;
output  [31:0] local_beta_buffer_27;
output   local_beta_buffer_27_ap_vld;
output  [31:0] local_beta_buffer_28;
output   local_beta_buffer_28_ap_vld;
output  [31:0] local_beta_buffer_29;
output   local_beta_buffer_29_ap_vld;
output  [31:0] local_beta_buffer_30;
output   local_beta_buffer_30_ap_vld;
output  [31:0] local_beta_buffer_31;
output   local_beta_buffer_31_ap_vld;
output  [31:0] local_beta_buffer_32;
output   local_beta_buffer_32_ap_vld;
output  [31:0] local_beta_buffer_33;
output   local_beta_buffer_33_ap_vld;
output  [31:0] local_beta_buffer_34;
output   local_beta_buffer_34_ap_vld;
output  [31:0] local_beta_buffer_35;
output   local_beta_buffer_35_ap_vld;
output  [31:0] local_beta_buffer_36;
output   local_beta_buffer_36_ap_vld;
output  [31:0] local_beta_buffer_37;
output   local_beta_buffer_37_ap_vld;
output  [31:0] local_beta_buffer_38;
output   local_beta_buffer_38_ap_vld;
output  [31:0] local_beta_buffer_39;
output   local_beta_buffer_39_ap_vld;
output  [31:0] local_beta_buffer_40;
output   local_beta_buffer_40_ap_vld;
output  [31:0] local_beta_buffer_41;
output   local_beta_buffer_41_ap_vld;
output  [31:0] local_beta_buffer_42;
output   local_beta_buffer_42_ap_vld;
output  [31:0] local_beta_buffer_43;
output   local_beta_buffer_43_ap_vld;
output  [31:0] local_beta_buffer_44;
output   local_beta_buffer_44_ap_vld;
output  [31:0] local_beta_buffer_45;
output   local_beta_buffer_45_ap_vld;
output  [31:0] local_beta_buffer_46;
output   local_beta_buffer_46_ap_vld;
output  [31:0] local_beta_buffer_47;
output   local_beta_buffer_47_ap_vld;
output  [31:0] local_beta_buffer_48;
output   local_beta_buffer_48_ap_vld;
output  [31:0] local_beta_buffer_49;
output   local_beta_buffer_49_ap_vld;
output  [31:0] local_beta_buffer_50;
output   local_beta_buffer_50_ap_vld;
output  [31:0] local_beta_buffer_51;
output   local_beta_buffer_51_ap_vld;
output  [31:0] local_beta_buffer_52;
output   local_beta_buffer_52_ap_vld;
output  [31:0] local_beta_buffer_53;
output   local_beta_buffer_53_ap_vld;
output  [31:0] local_beta_buffer_54;
output   local_beta_buffer_54_ap_vld;
output  [31:0] local_beta_buffer_55;
output   local_beta_buffer_55_ap_vld;
output  [31:0] local_beta_buffer_56;
output   local_beta_buffer_56_ap_vld;
output  [31:0] local_beta_buffer_57;
output   local_beta_buffer_57_ap_vld;
output  [31:0] local_beta_buffer_58;
output   local_beta_buffer_58_ap_vld;
output  [31:0] local_beta_buffer_59;
output   local_beta_buffer_59_ap_vld;

reg ap_idle;
reg local_beta_buffer_0_ap_vld;
reg bias_buffer_ce0;
reg local_beta_buffer_1_ap_vld;
reg local_beta_buffer_2_ap_vld;
reg local_beta_buffer_3_ap_vld;
reg local_beta_buffer_4_ap_vld;
reg local_beta_buffer_5_ap_vld;
reg local_beta_buffer_6_ap_vld;
reg local_beta_buffer_7_ap_vld;
reg local_beta_buffer_8_ap_vld;
reg local_beta_buffer_9_ap_vld;
reg local_beta_buffer_10_ap_vld;
reg local_beta_buffer_11_ap_vld;
reg local_beta_buffer_12_ap_vld;
reg local_beta_buffer_13_ap_vld;
reg local_beta_buffer_14_ap_vld;
reg local_beta_buffer_15_ap_vld;
reg local_beta_buffer_16_ap_vld;
reg local_beta_buffer_17_ap_vld;
reg local_beta_buffer_18_ap_vld;
reg local_beta_buffer_19_ap_vld;
reg local_beta_buffer_20_ap_vld;
reg local_beta_buffer_21_ap_vld;
reg local_beta_buffer_22_ap_vld;
reg local_beta_buffer_23_ap_vld;
reg local_beta_buffer_24_ap_vld;
reg local_beta_buffer_25_ap_vld;
reg local_beta_buffer_26_ap_vld;
reg local_beta_buffer_27_ap_vld;
reg local_beta_buffer_28_ap_vld;
reg local_beta_buffer_29_ap_vld;
reg local_beta_buffer_30_ap_vld;
reg local_beta_buffer_31_ap_vld;
reg local_beta_buffer_32_ap_vld;
reg local_beta_buffer_33_ap_vld;
reg local_beta_buffer_34_ap_vld;
reg local_beta_buffer_35_ap_vld;
reg local_beta_buffer_36_ap_vld;
reg local_beta_buffer_37_ap_vld;
reg local_beta_buffer_38_ap_vld;
reg local_beta_buffer_39_ap_vld;
reg local_beta_buffer_40_ap_vld;
reg local_beta_buffer_41_ap_vld;
reg local_beta_buffer_42_ap_vld;
reg local_beta_buffer_43_ap_vld;
reg local_beta_buffer_44_ap_vld;
reg local_beta_buffer_45_ap_vld;
reg local_beta_buffer_46_ap_vld;
reg local_beta_buffer_47_ap_vld;
reg local_beta_buffer_48_ap_vld;
reg local_beta_buffer_49_ap_vld;
reg local_beta_buffer_50_ap_vld;
reg local_beta_buffer_51_ap_vld;
reg local_beta_buffer_52_ap_vld;
reg local_beta_buffer_53_ap_vld;
reg local_beta_buffer_54_ap_vld;
reg local_beta_buffer_55_ap_vld;
reg local_beta_buffer_56_ap_vld;
reg local_beta_buffer_57_ap_vld;
reg local_beta_buffer_58_ap_vld;
reg local_beta_buffer_59_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln369_fu_334_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] InterSubBeta_cast_cast_fu_313_p1;
reg   [31:0] InterSubBeta_cast_cast_reg_764;
wire   [5:0] trunc_ln373_fu_353_p1;
reg   [5:0] trunc_ln373_reg_778;
reg   [5:0] trunc_ln373_reg_778_pp0_iter2_reg;
reg   [15:0] bias_buffer_load_reg_782;
wire   [63:0] zext_ln369_fu_348_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] tm_fu_274;
wire   [31:0] add_ln369_fu_339_p2;
wire    ap_loop_init;
reg   [33:0] offset_fu_278;
wire   [33:0] add_ln374_fu_360_p2;
wire  signed [33:0] sext_ln369_cast_fu_317_p1;
wire   [31:0] shl_ln373_fu_379_p2;
wire    ap_block_pp0_stage0_01001;
wire  signed [31:0] sext_ln373_fu_376_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

FPGA_Acc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            offset_fu_278 <= sext_ln369_cast_fu_317_p1;
        end else if (((icmp_ln369_fu_334_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            offset_fu_278 <= add_ln374_fu_360_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            tm_fu_274 <= 32'd0;
        end else if (((icmp_ln369_fu_334_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            tm_fu_274 <= add_ln369_fu_339_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        InterSubBeta_cast_cast_reg_764[4 : 0] <= InterSubBeta_cast_cast_fu_313_p1[4 : 0];
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        bias_buffer_load_reg_782 <= bias_buffer_q0;
        trunc_ln373_reg_778_pp0_iter2_reg <= trunc_ln373_reg_778;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln369_fu_334_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln373_reg_778 <= trunc_ln373_fu_353_p1;
    end
end

always @ (*) begin
    if (((icmp_ln369_fu_334_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buffer_ce0 = 1'b1;
    end else begin
        bias_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd0))) begin
        local_beta_buffer_0_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd10))) begin
        local_beta_buffer_10_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd11))) begin
        local_beta_buffer_11_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd12))) begin
        local_beta_buffer_12_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd13))) begin
        local_beta_buffer_13_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd14))) begin
        local_beta_buffer_14_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd15))) begin
        local_beta_buffer_15_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd16))) begin
        local_beta_buffer_16_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd17))) begin
        local_beta_buffer_17_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd18))) begin
        local_beta_buffer_18_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd19))) begin
        local_beta_buffer_19_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd1))) begin
        local_beta_buffer_1_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd20))) begin
        local_beta_buffer_20_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd21))) begin
        local_beta_buffer_21_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd22))) begin
        local_beta_buffer_22_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd23))) begin
        local_beta_buffer_23_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd24))) begin
        local_beta_buffer_24_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd25))) begin
        local_beta_buffer_25_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd26))) begin
        local_beta_buffer_26_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd27))) begin
        local_beta_buffer_27_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd28))) begin
        local_beta_buffer_28_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd29))) begin
        local_beta_buffer_29_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd2))) begin
        local_beta_buffer_2_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd30))) begin
        local_beta_buffer_30_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd31))) begin
        local_beta_buffer_31_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd32))) begin
        local_beta_buffer_32_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_32_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd33))) begin
        local_beta_buffer_33_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd34))) begin
        local_beta_buffer_34_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd35))) begin
        local_beta_buffer_35_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd36))) begin
        local_beta_buffer_36_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd37))) begin
        local_beta_buffer_37_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd38))) begin
        local_beta_buffer_38_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd39))) begin
        local_beta_buffer_39_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd3))) begin
        local_beta_buffer_3_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd40))) begin
        local_beta_buffer_40_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_40_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd41))) begin
        local_beta_buffer_41_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_41_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd42))) begin
        local_beta_buffer_42_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd43))) begin
        local_beta_buffer_43_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_43_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd44))) begin
        local_beta_buffer_44_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd45))) begin
        local_beta_buffer_45_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd46))) begin
        local_beta_buffer_46_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd47))) begin
        local_beta_buffer_47_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd48))) begin
        local_beta_buffer_48_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd49))) begin
        local_beta_buffer_49_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd4))) begin
        local_beta_buffer_4_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd50))) begin
        local_beta_buffer_50_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd51))) begin
        local_beta_buffer_51_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd52))) begin
        local_beta_buffer_52_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd53))) begin
        local_beta_buffer_53_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd54))) begin
        local_beta_buffer_54_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_54_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd55))) begin
        local_beta_buffer_55_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd56))) begin
        local_beta_buffer_56_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_56_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd57))) begin
        local_beta_buffer_57_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd58))) begin
        local_beta_buffer_58_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & ((trunc_ln373_reg_778_pp0_iter2_reg == 6'd59) | ((trunc_ln373_reg_778_pp0_iter2_reg == 6'd60) | ((trunc_ln373_reg_778_pp0_iter2_reg == 6'd61) | ((trunc_ln373_reg_778_pp0_iter2_reg == 6'd62) | (trunc_ln373_reg_778_pp0_iter2_reg == 6'd63))))))) begin
        local_beta_buffer_59_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd5))) begin
        local_beta_buffer_5_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd6))) begin
        local_beta_buffer_6_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd7))) begin
        local_beta_buffer_7_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd8))) begin
        local_beta_buffer_8_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln373_reg_778_pp0_iter2_reg == 6'd9))) begin
        local_beta_buffer_9_ap_vld = 1'b1;
    end else begin
        local_beta_buffer_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign InterSubBeta_cast_cast_fu_313_p1 = InterSubBeta_cast;

assign add_ln369_fu_339_p2 = (tm_fu_274 + 32'd1);

assign add_ln374_fu_360_p2 = (offset_fu_278 + 34'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bias_buffer_address0 = zext_ln369_fu_348_p1;

assign icmp_ln369_fu_334_p2 = ((tm_fu_274 == TM_MIN) ? 1'b1 : 1'b0);

assign local_beta_buffer_0 = shl_ln373_fu_379_p2;

assign local_beta_buffer_1 = shl_ln373_fu_379_p2;

assign local_beta_buffer_10 = shl_ln373_fu_379_p2;

assign local_beta_buffer_11 = shl_ln373_fu_379_p2;

assign local_beta_buffer_12 = shl_ln373_fu_379_p2;

assign local_beta_buffer_13 = shl_ln373_fu_379_p2;

assign local_beta_buffer_14 = shl_ln373_fu_379_p2;

assign local_beta_buffer_15 = shl_ln373_fu_379_p2;

assign local_beta_buffer_16 = shl_ln373_fu_379_p2;

assign local_beta_buffer_17 = shl_ln373_fu_379_p2;

assign local_beta_buffer_18 = shl_ln373_fu_379_p2;

assign local_beta_buffer_19 = shl_ln373_fu_379_p2;

assign local_beta_buffer_2 = shl_ln373_fu_379_p2;

assign local_beta_buffer_20 = shl_ln373_fu_379_p2;

assign local_beta_buffer_21 = shl_ln373_fu_379_p2;

assign local_beta_buffer_22 = shl_ln373_fu_379_p2;

assign local_beta_buffer_23 = shl_ln373_fu_379_p2;

assign local_beta_buffer_24 = shl_ln373_fu_379_p2;

assign local_beta_buffer_25 = shl_ln373_fu_379_p2;

assign local_beta_buffer_26 = shl_ln373_fu_379_p2;

assign local_beta_buffer_27 = shl_ln373_fu_379_p2;

assign local_beta_buffer_28 = shl_ln373_fu_379_p2;

assign local_beta_buffer_29 = shl_ln373_fu_379_p2;

assign local_beta_buffer_3 = shl_ln373_fu_379_p2;

assign local_beta_buffer_30 = shl_ln373_fu_379_p2;

assign local_beta_buffer_31 = shl_ln373_fu_379_p2;

assign local_beta_buffer_32 = shl_ln373_fu_379_p2;

assign local_beta_buffer_33 = shl_ln373_fu_379_p2;

assign local_beta_buffer_34 = shl_ln373_fu_379_p2;

assign local_beta_buffer_35 = shl_ln373_fu_379_p2;

assign local_beta_buffer_36 = shl_ln373_fu_379_p2;

assign local_beta_buffer_37 = shl_ln373_fu_379_p2;

assign local_beta_buffer_38 = shl_ln373_fu_379_p2;

assign local_beta_buffer_39 = shl_ln373_fu_379_p2;

assign local_beta_buffer_4 = shl_ln373_fu_379_p2;

assign local_beta_buffer_40 = shl_ln373_fu_379_p2;

assign local_beta_buffer_41 = shl_ln373_fu_379_p2;

assign local_beta_buffer_42 = shl_ln373_fu_379_p2;

assign local_beta_buffer_43 = shl_ln373_fu_379_p2;

assign local_beta_buffer_44 = shl_ln373_fu_379_p2;

assign local_beta_buffer_45 = shl_ln373_fu_379_p2;

assign local_beta_buffer_46 = shl_ln373_fu_379_p2;

assign local_beta_buffer_47 = shl_ln373_fu_379_p2;

assign local_beta_buffer_48 = shl_ln373_fu_379_p2;

assign local_beta_buffer_49 = shl_ln373_fu_379_p2;

assign local_beta_buffer_5 = shl_ln373_fu_379_p2;

assign local_beta_buffer_50 = shl_ln373_fu_379_p2;

assign local_beta_buffer_51 = shl_ln373_fu_379_p2;

assign local_beta_buffer_52 = shl_ln373_fu_379_p2;

assign local_beta_buffer_53 = shl_ln373_fu_379_p2;

assign local_beta_buffer_54 = shl_ln373_fu_379_p2;

assign local_beta_buffer_55 = shl_ln373_fu_379_p2;

assign local_beta_buffer_56 = shl_ln373_fu_379_p2;

assign local_beta_buffer_57 = shl_ln373_fu_379_p2;

assign local_beta_buffer_58 = shl_ln373_fu_379_p2;

assign local_beta_buffer_59 = shl_ln373_fu_379_p2;

assign local_beta_buffer_6 = shl_ln373_fu_379_p2;

assign local_beta_buffer_7 = shl_ln373_fu_379_p2;

assign local_beta_buffer_8 = shl_ln373_fu_379_p2;

assign local_beta_buffer_9 = shl_ln373_fu_379_p2;

assign sext_ln369_cast_fu_317_p1 = $signed(sext_ln369);

assign sext_ln373_fu_376_p1 = $signed(bias_buffer_load_reg_782);

assign shl_ln373_fu_379_p2 = sext_ln373_fu_376_p1 << InterSubBeta_cast_cast_reg_764;

assign trunc_ln373_fu_353_p1 = tm_fu_274[5:0];

assign zext_ln369_fu_348_p1 = offset_fu_278;

always @ (posedge ap_clk) begin
    InterSubBeta_cast_cast_reg_764[31:5] <= 27'b000000000000000000000000000;
end

endmodule //FPGA_Acc_conv2d_tile4_Pipeline_VITIS_LOOP_369_1
