// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FPGA_Acc_weight_load_reorg_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_BUS1_AWVALID,
        m_axi_DATA_BUS1_AWREADY,
        m_axi_DATA_BUS1_AWADDR,
        m_axi_DATA_BUS1_AWID,
        m_axi_DATA_BUS1_AWLEN,
        m_axi_DATA_BUS1_AWSIZE,
        m_axi_DATA_BUS1_AWBURST,
        m_axi_DATA_BUS1_AWLOCK,
        m_axi_DATA_BUS1_AWCACHE,
        m_axi_DATA_BUS1_AWPROT,
        m_axi_DATA_BUS1_AWQOS,
        m_axi_DATA_BUS1_AWREGION,
        m_axi_DATA_BUS1_AWUSER,
        m_axi_DATA_BUS1_WVALID,
        m_axi_DATA_BUS1_WREADY,
        m_axi_DATA_BUS1_WDATA,
        m_axi_DATA_BUS1_WSTRB,
        m_axi_DATA_BUS1_WLAST,
        m_axi_DATA_BUS1_WID,
        m_axi_DATA_BUS1_WUSER,
        m_axi_DATA_BUS1_ARVALID,
        m_axi_DATA_BUS1_ARREADY,
        m_axi_DATA_BUS1_ARADDR,
        m_axi_DATA_BUS1_ARID,
        m_axi_DATA_BUS1_ARLEN,
        m_axi_DATA_BUS1_ARSIZE,
        m_axi_DATA_BUS1_ARBURST,
        m_axi_DATA_BUS1_ARLOCK,
        m_axi_DATA_BUS1_ARCACHE,
        m_axi_DATA_BUS1_ARPROT,
        m_axi_DATA_BUS1_ARQOS,
        m_axi_DATA_BUS1_ARREGION,
        m_axi_DATA_BUS1_ARUSER,
        m_axi_DATA_BUS1_RVALID,
        m_axi_DATA_BUS1_RREADY,
        m_axi_DATA_BUS1_RDATA,
        m_axi_DATA_BUS1_RLAST,
        m_axi_DATA_BUS1_RID,
        m_axi_DATA_BUS1_RUSER,
        m_axi_DATA_BUS1_RRESP,
        m_axi_DATA_BUS1_BVALID,
        m_axi_DATA_BUS1_BREADY,
        m_axi_DATA_BUS1_BRESP,
        m_axi_DATA_BUS1_BID,
        m_axi_DATA_BUS1_BUSER,
        p_cast_cast,
        mm_offset,
        local_buf_address0,
        local_buf_ce0,
        local_buf_we0,
        local_buf_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_BUS1_AWVALID;
input   m_axi_DATA_BUS1_AWREADY;
output  [63:0] m_axi_DATA_BUS1_AWADDR;
output  [0:0] m_axi_DATA_BUS1_AWID;
output  [31:0] m_axi_DATA_BUS1_AWLEN;
output  [2:0] m_axi_DATA_BUS1_AWSIZE;
output  [1:0] m_axi_DATA_BUS1_AWBURST;
output  [1:0] m_axi_DATA_BUS1_AWLOCK;
output  [3:0] m_axi_DATA_BUS1_AWCACHE;
output  [2:0] m_axi_DATA_BUS1_AWPROT;
output  [3:0] m_axi_DATA_BUS1_AWQOS;
output  [3:0] m_axi_DATA_BUS1_AWREGION;
output  [0:0] m_axi_DATA_BUS1_AWUSER;
output   m_axi_DATA_BUS1_WVALID;
input   m_axi_DATA_BUS1_WREADY;
output  [31:0] m_axi_DATA_BUS1_WDATA;
output  [3:0] m_axi_DATA_BUS1_WSTRB;
output   m_axi_DATA_BUS1_WLAST;
output  [0:0] m_axi_DATA_BUS1_WID;
output  [0:0] m_axi_DATA_BUS1_WUSER;
output   m_axi_DATA_BUS1_ARVALID;
input   m_axi_DATA_BUS1_ARREADY;
output  [63:0] m_axi_DATA_BUS1_ARADDR;
output  [0:0] m_axi_DATA_BUS1_ARID;
output  [31:0] m_axi_DATA_BUS1_ARLEN;
output  [2:0] m_axi_DATA_BUS1_ARSIZE;
output  [1:0] m_axi_DATA_BUS1_ARBURST;
output  [1:0] m_axi_DATA_BUS1_ARLOCK;
output  [3:0] m_axi_DATA_BUS1_ARCACHE;
output  [2:0] m_axi_DATA_BUS1_ARPROT;
output  [3:0] m_axi_DATA_BUS1_ARQOS;
output  [3:0] m_axi_DATA_BUS1_ARREGION;
output  [0:0] m_axi_DATA_BUS1_ARUSER;
input   m_axi_DATA_BUS1_RVALID;
output   m_axi_DATA_BUS1_RREADY;
input  [31:0] m_axi_DATA_BUS1_RDATA;
input   m_axi_DATA_BUS1_RLAST;
input  [0:0] m_axi_DATA_BUS1_RID;
input  [0:0] m_axi_DATA_BUS1_RUSER;
input  [1:0] m_axi_DATA_BUS1_RRESP;
input   m_axi_DATA_BUS1_BVALID;
output   m_axi_DATA_BUS1_BREADY;
input  [1:0] m_axi_DATA_BUS1_BRESP;
input  [0:0] m_axi_DATA_BUS1_BID;
input  [0:0] m_axi_DATA_BUS1_BUSER;
input  [61:0] p_cast_cast;
input  [9:0] mm_offset;
output  [9:0] local_buf_address0;
output   local_buf_ce0;
output   local_buf_we0;
output  [31:0] local_buf_d0;

reg ap_idle;
reg m_axi_DATA_BUS1_RREADY;
reg local_buf_ce0;
reg local_buf_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] exitcond319_reg_142;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] exitcond319_fu_98_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    DATA_BUS1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] loop_index_load_reg_137;
reg   [9:0] loop_index_load_reg_137_pp0_iter1_reg;
reg   [31:0] DATA_BUS1_addr_read_reg_146;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] loop_index_cast_fu_121_p1;
reg   [9:0] loop_index_fu_52;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_loop_index_load;
wire   [9:0] empty_fu_104_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

FPGA_Acc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond319_fu_98_p2 == 1'd0))) begin
            loop_index_fu_52 <= empty_fu_104_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            loop_index_fu_52 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond319_reg_142 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DATA_BUS1_addr_read_reg_146 <= m_axi_DATA_BUS1_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        exitcond319_reg_142 <= exitcond319_fu_98_p2;
        loop_index_load_reg_137 <= ap_sig_allocacmp_loop_index_load;
        loop_index_load_reg_137_pp0_iter1_reg <= loop_index_load_reg_137;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond319_reg_142 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DATA_BUS1_blk_n_R = m_axi_DATA_BUS1_RVALID;
    end else begin
        DATA_BUS1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond319_fu_98_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond319_reg_142 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_loop_index_load = 10'd0;
    end else begin
        ap_sig_allocacmp_loop_index_load = loop_index_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_ce0 = 1'b1;
    end else begin
        local_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_we0 = 1'b1;
    end else begin
        local_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond319_reg_142 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_DATA_BUS1_RREADY = 1'b1;
    end else begin
        m_axi_DATA_BUS1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond319_reg_142 == 1'd0) & (m_axi_DATA_BUS1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond319_reg_142 == 1'd0) & (m_axi_DATA_BUS1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((exitcond319_reg_142 == 1'd0) & (m_axi_DATA_BUS1_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_fu_104_p2 = (ap_sig_allocacmp_loop_index_load + 10'd1);

assign exitcond319_fu_98_p2 = ((ap_sig_allocacmp_loop_index_load == mm_offset) ? 1'b1 : 1'b0);

assign local_buf_address0 = loop_index_cast_fu_121_p1;

assign local_buf_d0 = DATA_BUS1_addr_read_reg_146;

assign loop_index_cast_fu_121_p1 = loop_index_load_reg_137_pp0_iter1_reg;

assign m_axi_DATA_BUS1_ARADDR = 64'd0;

assign m_axi_DATA_BUS1_ARBURST = 2'd0;

assign m_axi_DATA_BUS1_ARCACHE = 4'd0;

assign m_axi_DATA_BUS1_ARID = 1'd0;

assign m_axi_DATA_BUS1_ARLEN = 32'd0;

assign m_axi_DATA_BUS1_ARLOCK = 2'd0;

assign m_axi_DATA_BUS1_ARPROT = 3'd0;

assign m_axi_DATA_BUS1_ARQOS = 4'd0;

assign m_axi_DATA_BUS1_ARREGION = 4'd0;

assign m_axi_DATA_BUS1_ARSIZE = 3'd0;

assign m_axi_DATA_BUS1_ARUSER = 1'd0;

assign m_axi_DATA_BUS1_ARVALID = 1'b0;

assign m_axi_DATA_BUS1_AWADDR = 64'd0;

assign m_axi_DATA_BUS1_AWBURST = 2'd0;

assign m_axi_DATA_BUS1_AWCACHE = 4'd0;

assign m_axi_DATA_BUS1_AWID = 1'd0;

assign m_axi_DATA_BUS1_AWLEN = 32'd0;

assign m_axi_DATA_BUS1_AWLOCK = 2'd0;

assign m_axi_DATA_BUS1_AWPROT = 3'd0;

assign m_axi_DATA_BUS1_AWQOS = 4'd0;

assign m_axi_DATA_BUS1_AWREGION = 4'd0;

assign m_axi_DATA_BUS1_AWSIZE = 3'd0;

assign m_axi_DATA_BUS1_AWUSER = 1'd0;

assign m_axi_DATA_BUS1_AWVALID = 1'b0;

assign m_axi_DATA_BUS1_BREADY = 1'b0;

assign m_axi_DATA_BUS1_WDATA = 32'd0;

assign m_axi_DATA_BUS1_WID = 1'd0;

assign m_axi_DATA_BUS1_WLAST = 1'b0;

assign m_axi_DATA_BUS1_WSTRB = 4'd0;

assign m_axi_DATA_BUS1_WUSER = 1'd0;

assign m_axi_DATA_BUS1_WVALID = 1'b0;

endmodule //FPGA_Acc_weight_load_reorg_Pipeline_1
