// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FPGA_Acc_ifm_copy_lbuf2ibuf (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_buffer_0_address0,
        input_buffer_0_ce0,
        input_buffer_0_we0,
        input_buffer_0_d0,
        input_buffer_1_address0,
        input_buffer_1_ce0,
        input_buffer_1_we0,
        input_buffer_1_d0,
        local_buf_address0,
        local_buf_ce0,
        local_buf_q0,
        TCol,
        Input_w,
        Input_h,
        TN_MIN,
        pad_val,
        Coffset,
        Roffset,
        t1,
        t2,
        bn,
        enable
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] input_buffer_0_address0;
output   input_buffer_0_ce0;
output   input_buffer_0_we0;
output  [15:0] input_buffer_0_d0;
output  [11:0] input_buffer_1_address0;
output   input_buffer_1_ce0;
output   input_buffer_1_we0;
output  [15:0] input_buffer_1_d0;
output  [4:0] local_buf_address0;
output   local_buf_ce0;
input  [31:0] local_buf_q0;
input  [15:0] TCol;
input  [11:0] Input_w;
input  [11:0] Input_h;
input  [7:0] TN_MIN;
input  [15:0] pad_val;
input  [17:0] Coffset;
input  [17:0] Roffset;
input  [7:0] t1;
input  [7:0] t2;
input  [7:0] bn;
input   enable;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] local_buf_address0;
reg local_buf_ce0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] enable_read_read_fu_56_p2;
wire   [0:0] TN_Enable_fu_160_p2;
reg   [0:0] TN_Enable_reg_279;
wire   [18:0] yoffset_fu_170_p2;
reg   [18:0] yoffset_reg_284;
wire   [0:0] trunc_ln51_fu_176_p1;
reg   [0:0] trunc_ln51_reg_290;
wire   [15:0] buf_256b_0_fu_201_p1;
reg   [15:0] buf_256b_0_reg_295;
wire    ap_CS_fsm_state2;
reg   [15:0] buf_256b_1_reg_300;
wire   [11:0] mul_ln51_fu_218_p2;
reg   [11:0] mul_ln51_reg_305;
wire   [0:0] and_ln49_2_fu_230_p2;
reg   [0:0] and_ln49_2_reg_310;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_done;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_idle;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_ready;
wire   [4:0] grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_local_buf_address0;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_local_buf_ce0;
wire   [11:0] grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_address0;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_ce0;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_we0;
wire   [15:0] grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_d0;
wire   [11:0] grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_address0;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_ce0;
wire    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_we0;
wire   [15:0] grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_d0;
reg    grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [18:0] zext_ln33_fu_166_p1;
wire  signed [18:0] Roffset_cast_fu_156_p1;
wire   [0:0] tmp_fu_180_p3;
wire   [18:0] zext_ln34_fu_193_p1;
wire   [7:0] mul_ln51_fu_218_p0;
wire   [6:0] mul_ln51_fu_218_p1;
wire   [0:0] icmp_ln34_fu_196_p2;
wire   [0:0] xor_ln34_fu_187_p2;
wire   [0:0] and_ln49_fu_224_p2;
reg    ap_block_state4_on_subcall_done;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire   [11:0] mul_ln51_fu_218_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start_reg = 1'b0;
end

FPGA_Acc_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1 grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start),
    .ap_done(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_done),
    .ap_idle(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_idle),
    .ap_ready(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_ready),
    .buf_256b_1(buf_256b_1_reg_300),
    .buf_256b_0(buf_256b_0_reg_295),
    .bn(bn),
    .TCol(TCol),
    .local_buf_address0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_local_buf_address0),
    .local_buf_ce0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_local_buf_ce0),
    .local_buf_q0(local_buf_q0),
    .Coffset_cast(Coffset),
    .Input_w_cast(Input_w),
    .and_ln49_3(and_ln49_2_reg_310),
    .mul_ln51(mul_ln51_reg_305),
    .input_buffer_0_address0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_address0),
    .input_buffer_0_ce0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_ce0),
    .input_buffer_0_we0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_we0),
    .input_buffer_0_d0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_d0),
    .input_buffer_1_address0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_address0),
    .input_buffer_1_ce0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_ce0),
    .input_buffer_1_we0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_we0),
    .input_buffer_1_d0(grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_d0),
    .pad_val(pad_val),
    .trunc_ln(trunc_ln51_reg_290)
);

FPGA_Acc_mul_8ns_7ns_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
mul_8ns_7ns_12_1_1_U27(
    .din0(mul_ln51_fu_218_p0),
    .din1(mul_ln51_fu_218_p1),
    .dout(mul_ln51_fu_218_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_ready == 1'b1)) begin
            grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((enable_read_read_fu_56_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        TN_Enable_reg_279 <= TN_Enable_fu_160_p2;
        trunc_ln51_reg_290 <= trunc_ln51_fu_176_p1;
        yoffset_reg_284 <= yoffset_fu_170_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        and_ln49_2_reg_310 <= and_ln49_2_fu_230_p2;
        buf_256b_0_reg_295 <= buf_256b_0_fu_201_p1;
        buf_256b_1_reg_300 <= {{local_buf_q0[31:16]}};
        mul_ln51_reg_305 <= mul_ln51_fu_218_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        local_buf_address0 = 64'd0;
    end else if (((enable_read_read_fu_56_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        local_buf_address0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_local_buf_address0;
    end else begin
        local_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        local_buf_ce0 = 1'b1;
    end else if (((enable_read_read_fu_56_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        local_buf_ce0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_local_buf_ce0;
    end else begin
        local_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (enable_read_read_fu_56_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((ap_start == 1'b1) & (enable_read_read_fu_56_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Roffset_cast_fu_156_p1 = $signed(Roffset);

assign TN_Enable_fu_160_p2 = ((t1 < TN_MIN) ? 1'b1 : 1'b0);

assign and_ln49_2_fu_230_p2 = (and_ln49_fu_224_p2 & TN_Enable_reg_279);

assign and_ln49_fu_224_p2 = (xor_ln34_fu_187_p2 & icmp_ln34_fu_196_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_done == 1'b0) & (enable_read_read_fu_56_p2 == 1'd1));
end

assign buf_256b_0_fu_201_p1 = local_buf_q0[15:0];

assign enable_read_read_fu_56_p2 = enable;

assign grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_ap_start_reg;

assign icmp_ln34_fu_196_p2 = (($signed(yoffset_reg_284) < $signed(zext_ln34_fu_193_p1)) ? 1'b1 : 1'b0);

assign input_buffer_0_address0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_address0;

assign input_buffer_0_ce0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_ce0;

assign input_buffer_0_d0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_d0;

assign input_buffer_0_we0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_0_we0;

assign input_buffer_1_address0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_address0;

assign input_buffer_1_ce0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_ce0;

assign input_buffer_1_d0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_d0;

assign input_buffer_1_we0 = grp_ifm_copy_lbuf2ibuf_Pipeline_VITIS_LOOP_43_1_fu_136_input_buffer_1_we0;

assign mul_ln51_fu_218_p0 = mul_ln51_fu_218_p00;

assign mul_ln51_fu_218_p00 = t2;

assign mul_ln51_fu_218_p1 = 12'd53;

assign tmp_fu_180_p3 = yoffset_reg_284[32'd18];

assign trunc_ln51_fu_176_p1 = t1[0:0];

assign xor_ln34_fu_187_p2 = (tmp_fu_180_p3 ^ 1'd1);

assign yoffset_fu_170_p2 = ($signed(zext_ln33_fu_166_p1) + $signed(Roffset_cast_fu_156_p1));

assign zext_ln33_fu_166_p1 = t2;

assign zext_ln34_fu_193_p1 = Input_h;

endmodule //FPGA_Acc_ifm_copy_lbuf2ibuf
