// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FPGA_Acc_nonlinear_leaky_row (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_buf_address0,
        local_buf_ce0,
        local_buf_we0,
        local_buf_d0,
        Input_0_address0,
        Input_0_ce0,
        Input_0_q0,
        Input_1_address0,
        Input_1_ce0,
        Input_1_q0,
        Input_2_address0,
        Input_2_ce0,
        Input_2_q0,
        Input_3_address0,
        Input_3_ce0,
        Input_3_q0,
        Input_4_address0,
        Input_4_ce0,
        Input_4_q0,
        Input_5_address0,
        Input_5_ce0,
        Input_5_q0,
        Input_6_address0,
        Input_6_ce0,
        Input_6_q0,
        Input_7_address0,
        Input_7_ce0,
        Input_7_q0,
        Input_8_address0,
        Input_8_ce0,
        Input_8_q0,
        Input_9_address0,
        Input_9_ce0,
        Input_9_q0,
        Input_10_address0,
        Input_10_ce0,
        Input_10_q0,
        Input_11_address0,
        Input_11_ce0,
        Input_11_q0,
        Input_12_address0,
        Input_12_ce0,
        Input_12_q0,
        Input_13_address0,
        Input_13_ce0,
        Input_13_q0,
        Input_14_address0,
        Input_14_ce0,
        Input_14_q0,
        Input_15_address0,
        Input_15_ce0,
        Input_15_q0,
        Input_16_address0,
        Input_16_ce0,
        Input_16_q0,
        Input_17_address0,
        Input_17_ce0,
        Input_17_q0,
        Input_18_address0,
        Input_18_ce0,
        Input_18_q0,
        Input_19_address0,
        Input_19_ce0,
        Input_19_q0,
        Input_20_address0,
        Input_20_ce0,
        Input_20_q0,
        Input_21_address0,
        Input_21_ce0,
        Input_21_q0,
        Input_22_address0,
        Input_22_ce0,
        Input_22_q0,
        Input_23_address0,
        Input_23_ce0,
        Input_23_q0,
        Input_24_address0,
        Input_24_ce0,
        Input_24_q0,
        Input_25_address0,
        Input_25_ce0,
        Input_25_q0,
        Input_26_address0,
        Input_26_ce0,
        Input_26_q0,
        Input_27_address0,
        Input_27_ce0,
        Input_27_q0,
        Input_28_address0,
        Input_28_ce0,
        Input_28_q0,
        Input_29_address0,
        Input_29_ce0,
        Input_29_q0,
        Input_30_address0,
        Input_30_ce0,
        Input_30_q0,
        Input_31_address0,
        Input_31_ce0,
        Input_31_q0,
        Input_32_address0,
        Input_32_ce0,
        Input_32_q0,
        Input_33_address0,
        Input_33_ce0,
        Input_33_q0,
        Input_34_address0,
        Input_34_ce0,
        Input_34_q0,
        Input_35_address0,
        Input_35_ce0,
        Input_35_q0,
        Input_36_address0,
        Input_36_ce0,
        Input_36_q0,
        Input_37_address0,
        Input_37_ce0,
        Input_37_q0,
        Input_38_address0,
        Input_38_ce0,
        Input_38_q0,
        Input_39_address0,
        Input_39_ce0,
        Input_39_q0,
        Input_40_address0,
        Input_40_ce0,
        Input_40_q0,
        Input_41_address0,
        Input_41_ce0,
        Input_41_q0,
        Input_42_address0,
        Input_42_ce0,
        Input_42_q0,
        Input_43_address0,
        Input_43_ce0,
        Input_43_q0,
        Input_44_address0,
        Input_44_ce0,
        Input_44_q0,
        Input_45_address0,
        Input_45_ce0,
        Input_45_q0,
        Input_46_address0,
        Input_46_ce0,
        Input_46_q0,
        Input_47_address0,
        Input_47_ce0,
        Input_47_q0,
        Input_48_address0,
        Input_48_ce0,
        Input_48_q0,
        Input_49_address0,
        Input_49_ce0,
        Input_49_q0,
        Input_50_address0,
        Input_50_ce0,
        Input_50_q0,
        Input_51_address0,
        Input_51_ce0,
        Input_51_q0,
        Input_52_address0,
        Input_52_ce0,
        Input_52_q0,
        Input_53_address0,
        Input_53_ce0,
        Input_53_q0,
        Input_54_address0,
        Input_54_ce0,
        Input_54_q0,
        Input_55_address0,
        Input_55_ce0,
        Input_55_q0,
        Input_56_address0,
        Input_56_ce0,
        Input_56_q0,
        Input_57_address0,
        Input_57_ce0,
        Input_57_q0,
        Input_58_address0,
        Input_58_ce0,
        Input_58_q0,
        Input_59_address0,
        Input_59_ce0,
        Input_59_q0,
        tm,
        tr,
        tm_n_read,
        tr_n_read,
        TC_MIN,
        IsNL,
        enable,
        InterSubOutput,
        ltype,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] local_buf_address0;
output   local_buf_ce0;
output   local_buf_we0;
output  [31:0] local_buf_d0;
output  [9:0] Input_0_address0;
output   Input_0_ce0;
input  [31:0] Input_0_q0;
output  [9:0] Input_1_address0;
output   Input_1_ce0;
input  [31:0] Input_1_q0;
output  [9:0] Input_2_address0;
output   Input_2_ce0;
input  [31:0] Input_2_q0;
output  [9:0] Input_3_address0;
output   Input_3_ce0;
input  [31:0] Input_3_q0;
output  [9:0] Input_4_address0;
output   Input_4_ce0;
input  [31:0] Input_4_q0;
output  [9:0] Input_5_address0;
output   Input_5_ce0;
input  [31:0] Input_5_q0;
output  [9:0] Input_6_address0;
output   Input_6_ce0;
input  [31:0] Input_6_q0;
output  [9:0] Input_7_address0;
output   Input_7_ce0;
input  [31:0] Input_7_q0;
output  [9:0] Input_8_address0;
output   Input_8_ce0;
input  [31:0] Input_8_q0;
output  [9:0] Input_9_address0;
output   Input_9_ce0;
input  [31:0] Input_9_q0;
output  [9:0] Input_10_address0;
output   Input_10_ce0;
input  [31:0] Input_10_q0;
output  [9:0] Input_11_address0;
output   Input_11_ce0;
input  [31:0] Input_11_q0;
output  [9:0] Input_12_address0;
output   Input_12_ce0;
input  [31:0] Input_12_q0;
output  [9:0] Input_13_address0;
output   Input_13_ce0;
input  [31:0] Input_13_q0;
output  [9:0] Input_14_address0;
output   Input_14_ce0;
input  [31:0] Input_14_q0;
output  [9:0] Input_15_address0;
output   Input_15_ce0;
input  [31:0] Input_15_q0;
output  [9:0] Input_16_address0;
output   Input_16_ce0;
input  [31:0] Input_16_q0;
output  [9:0] Input_17_address0;
output   Input_17_ce0;
input  [31:0] Input_17_q0;
output  [9:0] Input_18_address0;
output   Input_18_ce0;
input  [31:0] Input_18_q0;
output  [9:0] Input_19_address0;
output   Input_19_ce0;
input  [31:0] Input_19_q0;
output  [9:0] Input_20_address0;
output   Input_20_ce0;
input  [31:0] Input_20_q0;
output  [9:0] Input_21_address0;
output   Input_21_ce0;
input  [31:0] Input_21_q0;
output  [9:0] Input_22_address0;
output   Input_22_ce0;
input  [31:0] Input_22_q0;
output  [9:0] Input_23_address0;
output   Input_23_ce0;
input  [31:0] Input_23_q0;
output  [9:0] Input_24_address0;
output   Input_24_ce0;
input  [31:0] Input_24_q0;
output  [9:0] Input_25_address0;
output   Input_25_ce0;
input  [31:0] Input_25_q0;
output  [9:0] Input_26_address0;
output   Input_26_ce0;
input  [31:0] Input_26_q0;
output  [9:0] Input_27_address0;
output   Input_27_ce0;
input  [31:0] Input_27_q0;
output  [9:0] Input_28_address0;
output   Input_28_ce0;
input  [31:0] Input_28_q0;
output  [9:0] Input_29_address0;
output   Input_29_ce0;
input  [31:0] Input_29_q0;
output  [9:0] Input_30_address0;
output   Input_30_ce0;
input  [31:0] Input_30_q0;
output  [9:0] Input_31_address0;
output   Input_31_ce0;
input  [31:0] Input_31_q0;
output  [9:0] Input_32_address0;
output   Input_32_ce0;
input  [31:0] Input_32_q0;
output  [9:0] Input_33_address0;
output   Input_33_ce0;
input  [31:0] Input_33_q0;
output  [9:0] Input_34_address0;
output   Input_34_ce0;
input  [31:0] Input_34_q0;
output  [9:0] Input_35_address0;
output   Input_35_ce0;
input  [31:0] Input_35_q0;
output  [9:0] Input_36_address0;
output   Input_36_ce0;
input  [31:0] Input_36_q0;
output  [9:0] Input_37_address0;
output   Input_37_ce0;
input  [31:0] Input_37_q0;
output  [9:0] Input_38_address0;
output   Input_38_ce0;
input  [31:0] Input_38_q0;
output  [9:0] Input_39_address0;
output   Input_39_ce0;
input  [31:0] Input_39_q0;
output  [9:0] Input_40_address0;
output   Input_40_ce0;
input  [31:0] Input_40_q0;
output  [9:0] Input_41_address0;
output   Input_41_ce0;
input  [31:0] Input_41_q0;
output  [9:0] Input_42_address0;
output   Input_42_ce0;
input  [31:0] Input_42_q0;
output  [9:0] Input_43_address0;
output   Input_43_ce0;
input  [31:0] Input_43_q0;
output  [9:0] Input_44_address0;
output   Input_44_ce0;
input  [31:0] Input_44_q0;
output  [9:0] Input_45_address0;
output   Input_45_ce0;
input  [31:0] Input_45_q0;
output  [9:0] Input_46_address0;
output   Input_46_ce0;
input  [31:0] Input_46_q0;
output  [9:0] Input_47_address0;
output   Input_47_ce0;
input  [31:0] Input_47_q0;
output  [9:0] Input_48_address0;
output   Input_48_ce0;
input  [31:0] Input_48_q0;
output  [9:0] Input_49_address0;
output   Input_49_ce0;
input  [31:0] Input_49_q0;
output  [9:0] Input_50_address0;
output   Input_50_ce0;
input  [31:0] Input_50_q0;
output  [9:0] Input_51_address0;
output   Input_51_ce0;
input  [31:0] Input_51_q0;
output  [9:0] Input_52_address0;
output   Input_52_ce0;
input  [31:0] Input_52_q0;
output  [9:0] Input_53_address0;
output   Input_53_ce0;
input  [31:0] Input_53_q0;
output  [9:0] Input_54_address0;
output   Input_54_ce0;
input  [31:0] Input_54_q0;
output  [9:0] Input_55_address0;
output   Input_55_ce0;
input  [31:0] Input_55_q0;
output  [9:0] Input_56_address0;
output   Input_56_ce0;
input  [31:0] Input_56_q0;
output  [9:0] Input_57_address0;
output   Input_57_ce0;
input  [31:0] Input_57_q0;
output  [9:0] Input_58_address0;
output   Input_58_ce0;
input  [31:0] Input_58_q0;
output  [9:0] Input_59_address0;
output   Input_59_ce0;
input  [31:0] Input_59_q0;
input  [7:0] tm;
input  [7:0] tr;
input  [7:0] tm_n_read;
input  [7:0] tr_n_read;
input  [7:0] TC_MIN;
input   IsNL;
input   enable;
input  [4:0] InterSubOutput;
input  [7:0] ltype;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] local_buf_address0;
reg local_buf_ce0;
reg local_buf_we0;
reg[31:0] local_buf_d0;
reg[7:0] ap_return_0;
reg[7:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] enable_read_read_fu_190_p2;
wire   [9:0] mul_ln186_fu_403_p2;
reg   [9:0] mul_ln186_reg_527;
wire   [0:0] cmp15_fu_409_p2;
reg   [0:0] cmp15_reg_532;
wire   [5:0] trunc_ln186_fu_415_p1;
reg   [5:0] trunc_ln186_reg_537;
wire    ap_CS_fsm_state2;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_done;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_idle;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_ready;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_0_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_0_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_1_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_1_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_2_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_2_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_3_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_3_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_4_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_4_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_5_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_5_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_6_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_6_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_7_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_7_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_8_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_8_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_9_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_9_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_10_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_10_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_11_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_11_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_12_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_12_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_13_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_13_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_14_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_14_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_15_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_15_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_16_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_16_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_17_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_17_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_18_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_18_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_19_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_19_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_20_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_20_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_21_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_21_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_22_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_22_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_23_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_23_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_24_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_24_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_25_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_25_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_26_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_26_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_27_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_27_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_28_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_28_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_29_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_29_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_30_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_30_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_31_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_31_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_32_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_32_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_33_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_33_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_34_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_34_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_35_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_35_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_36_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_36_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_37_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_37_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_38_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_38_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_39_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_39_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_40_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_40_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_41_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_41_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_42_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_42_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_43_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_43_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_44_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_44_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_45_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_45_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_46_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_46_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_47_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_47_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_48_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_48_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_49_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_49_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_50_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_50_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_51_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_51_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_52_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_52_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_53_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_53_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_54_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_54_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_55_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_55_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_56_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_56_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_57_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_57_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_58_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_58_ce0;
wire   [9:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_59_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_59_ce0;
wire   [0:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_IsNL;
wire   [3:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_address0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_ce0;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_we0;
wire   [31:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_d0;
wire   [15:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_1_0121_out;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_1_0121_out_ap_vld;
wire   [15:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_0_0120_out;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_0_0120_out_ap_vld;
wire   [3:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_bn_local_out;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_bn_local_out_ap_vld;
wire   [3:0] grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_cnt_out;
wire    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_cnt_out_ap_vld;
reg   [7:0] ap_phi_mux_phi_ln224_phi_fu_248_p4;
reg   [7:0] phi_ln224_reg_245;
wire    ap_CS_fsm_state4;
reg   [7:0] ap_phi_mux_phi_ln224_1_phi_fu_257_p4;
reg   [7:0] phi_ln224_1_reg_254;
reg    grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [3:0] cnt_loc_fu_162;
wire   [63:0] zext_ln219_fu_446_p1;
wire   [0:0] icmp_ln217_fu_431_p2;
wire   [31:0] or1_fu_437_p3;
wire   [7:0] mul_ln186_fu_403_p0;
wire   [5:0] mul_ln186_fu_403_p1;
reg   [7:0] ap_return_0_preg;
reg   [7:0] ap_return_1_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire   [9:0] mul_ln186_fu_403_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 8'd0;
#0 ap_return_1_preg = 8'd0;
end

FPGA_Acc_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1 grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start),
    .ap_done(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_done),
    .ap_idle(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_idle),
    .ap_ready(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_ready),
    .TC_MIN(TC_MIN),
    .mul_ln186(mul_ln186_reg_527),
    .Input_0_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_0_address0),
    .Input_0_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_0_ce0),
    .Input_0_q0(Input_0_q0),
    .Input_1_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_1_address0),
    .Input_1_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_1_ce0),
    .Input_1_q0(Input_1_q0),
    .Input_2_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_2_address0),
    .Input_2_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_2_ce0),
    .Input_2_q0(Input_2_q0),
    .Input_3_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_3_address0),
    .Input_3_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_3_ce0),
    .Input_3_q0(Input_3_q0),
    .Input_4_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_4_address0),
    .Input_4_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_4_ce0),
    .Input_4_q0(Input_4_q0),
    .Input_5_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_5_address0),
    .Input_5_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_5_ce0),
    .Input_5_q0(Input_5_q0),
    .Input_6_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_6_address0),
    .Input_6_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_6_ce0),
    .Input_6_q0(Input_6_q0),
    .Input_7_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_7_address0),
    .Input_7_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_7_ce0),
    .Input_7_q0(Input_7_q0),
    .Input_8_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_8_address0),
    .Input_8_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_8_ce0),
    .Input_8_q0(Input_8_q0),
    .Input_9_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_9_address0),
    .Input_9_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_9_ce0),
    .Input_9_q0(Input_9_q0),
    .Input_10_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_10_address0),
    .Input_10_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_10_ce0),
    .Input_10_q0(Input_10_q0),
    .Input_11_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_11_address0),
    .Input_11_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_11_ce0),
    .Input_11_q0(Input_11_q0),
    .Input_12_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_12_address0),
    .Input_12_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_12_ce0),
    .Input_12_q0(Input_12_q0),
    .Input_13_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_13_address0),
    .Input_13_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_13_ce0),
    .Input_13_q0(Input_13_q0),
    .Input_14_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_14_address0),
    .Input_14_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_14_ce0),
    .Input_14_q0(Input_14_q0),
    .Input_15_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_15_address0),
    .Input_15_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_15_ce0),
    .Input_15_q0(Input_15_q0),
    .Input_16_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_16_address0),
    .Input_16_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_16_ce0),
    .Input_16_q0(Input_16_q0),
    .Input_17_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_17_address0),
    .Input_17_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_17_ce0),
    .Input_17_q0(Input_17_q0),
    .Input_18_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_18_address0),
    .Input_18_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_18_ce0),
    .Input_18_q0(Input_18_q0),
    .Input_19_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_19_address0),
    .Input_19_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_19_ce0),
    .Input_19_q0(Input_19_q0),
    .Input_20_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_20_address0),
    .Input_20_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_20_ce0),
    .Input_20_q0(Input_20_q0),
    .Input_21_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_21_address0),
    .Input_21_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_21_ce0),
    .Input_21_q0(Input_21_q0),
    .Input_22_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_22_address0),
    .Input_22_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_22_ce0),
    .Input_22_q0(Input_22_q0),
    .Input_23_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_23_address0),
    .Input_23_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_23_ce0),
    .Input_23_q0(Input_23_q0),
    .Input_24_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_24_address0),
    .Input_24_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_24_ce0),
    .Input_24_q0(Input_24_q0),
    .Input_25_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_25_address0),
    .Input_25_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_25_ce0),
    .Input_25_q0(Input_25_q0),
    .Input_26_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_26_address0),
    .Input_26_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_26_ce0),
    .Input_26_q0(Input_26_q0),
    .Input_27_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_27_address0),
    .Input_27_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_27_ce0),
    .Input_27_q0(Input_27_q0),
    .Input_28_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_28_address0),
    .Input_28_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_28_ce0),
    .Input_28_q0(Input_28_q0),
    .Input_29_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_29_address0),
    .Input_29_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_29_ce0),
    .Input_29_q0(Input_29_q0),
    .Input_30_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_30_address0),
    .Input_30_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_30_ce0),
    .Input_30_q0(Input_30_q0),
    .Input_31_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_31_address0),
    .Input_31_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_31_ce0),
    .Input_31_q0(Input_31_q0),
    .Input_32_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_32_address0),
    .Input_32_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_32_ce0),
    .Input_32_q0(Input_32_q0),
    .Input_33_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_33_address0),
    .Input_33_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_33_ce0),
    .Input_33_q0(Input_33_q0),
    .Input_34_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_34_address0),
    .Input_34_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_34_ce0),
    .Input_34_q0(Input_34_q0),
    .Input_35_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_35_address0),
    .Input_35_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_35_ce0),
    .Input_35_q0(Input_35_q0),
    .Input_36_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_36_address0),
    .Input_36_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_36_ce0),
    .Input_36_q0(Input_36_q0),
    .Input_37_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_37_address0),
    .Input_37_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_37_ce0),
    .Input_37_q0(Input_37_q0),
    .Input_38_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_38_address0),
    .Input_38_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_38_ce0),
    .Input_38_q0(Input_38_q0),
    .Input_39_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_39_address0),
    .Input_39_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_39_ce0),
    .Input_39_q0(Input_39_q0),
    .Input_40_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_40_address0),
    .Input_40_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_40_ce0),
    .Input_40_q0(Input_40_q0),
    .Input_41_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_41_address0),
    .Input_41_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_41_ce0),
    .Input_41_q0(Input_41_q0),
    .Input_42_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_42_address0),
    .Input_42_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_42_ce0),
    .Input_42_q0(Input_42_q0),
    .Input_43_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_43_address0),
    .Input_43_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_43_ce0),
    .Input_43_q0(Input_43_q0),
    .Input_44_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_44_address0),
    .Input_44_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_44_ce0),
    .Input_44_q0(Input_44_q0),
    .Input_45_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_45_address0),
    .Input_45_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_45_ce0),
    .Input_45_q0(Input_45_q0),
    .Input_46_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_46_address0),
    .Input_46_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_46_ce0),
    .Input_46_q0(Input_46_q0),
    .Input_47_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_47_address0),
    .Input_47_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_47_ce0),
    .Input_47_q0(Input_47_q0),
    .Input_48_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_48_address0),
    .Input_48_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_48_ce0),
    .Input_48_q0(Input_48_q0),
    .Input_49_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_49_address0),
    .Input_49_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_49_ce0),
    .Input_49_q0(Input_49_q0),
    .Input_50_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_50_address0),
    .Input_50_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_50_ce0),
    .Input_50_q0(Input_50_q0),
    .Input_51_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_51_address0),
    .Input_51_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_51_ce0),
    .Input_51_q0(Input_51_q0),
    .Input_52_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_52_address0),
    .Input_52_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_52_ce0),
    .Input_52_q0(Input_52_q0),
    .Input_53_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_53_address0),
    .Input_53_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_53_ce0),
    .Input_53_q0(Input_53_q0),
    .Input_54_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_54_address0),
    .Input_54_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_54_ce0),
    .Input_54_q0(Input_54_q0),
    .Input_55_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_55_address0),
    .Input_55_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_55_ce0),
    .Input_55_q0(Input_55_q0),
    .Input_56_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_56_address0),
    .Input_56_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_56_ce0),
    .Input_56_q0(Input_56_q0),
    .Input_57_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_57_address0),
    .Input_57_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_57_ce0),
    .Input_57_q0(Input_57_q0),
    .Input_58_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_58_address0),
    .Input_58_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_58_ce0),
    .Input_58_q0(Input_58_q0),
    .Input_59_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_59_address0),
    .Input_59_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_59_ce0),
    .Input_59_q0(Input_59_q0),
    .trunc_ln(trunc_ln186_reg_537),
    .IsNL(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_IsNL),
    .InterSubOutput_cast(InterSubOutput),
    .cmp15(cmp15_reg_532),
    .local_buf_address0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_address0),
    .local_buf_ce0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_ce0),
    .local_buf_we0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_we0),
    .local_buf_d0(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_d0),
    .buf_256b_1_0121_out(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_1_0121_out),
    .buf_256b_1_0121_out_ap_vld(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_1_0121_out_ap_vld),
    .buf_256b_0_0120_out(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_0_0120_out),
    .buf_256b_0_0120_out_ap_vld(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_0_0120_out_ap_vld),
    .bn_local_out(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_bn_local_out),
    .bn_local_out_ap_vld(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_bn_local_out_ap_vld),
    .cnt_out(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_cnt_out),
    .cnt_out_ap_vld(grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_cnt_out_ap_vld)
);

FPGA_Acc_mul_8ns_6ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 10 ))
mul_8ns_6ns_10_1_1_U1388(
    .din0(mul_ln186_fu_403_p0),
    .din1(mul_ln186_fu_403_p1),
    .dout(mul_ln186_fu_403_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 8'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_return_0_preg <= ap_phi_mux_phi_ln224_1_phi_fu_257_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 8'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_return_1_preg <= ap_phi_mux_phi_ln224_phi_fu_248_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start_reg <= 1'b1;
        end else if ((grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_ready == 1'b1)) begin
            grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (enable_read_read_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln224_1_reg_254 <= tm_n_read;
    end else if (((enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_ln224_1_reg_254 <= tm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (enable_read_read_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_ln224_reg_245 <= tr_n_read;
    end else if (((enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_ln224_reg_245 <= tr;
    end
end

always @ (posedge ap_clk) begin
    if (((enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        cmp15_reg_532 <= cmp15_fu_409_p2;
        mul_ln186_reg_527 <= mul_ln186_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_cnt_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        cnt_loc_fu_162 <= grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_cnt_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln186_reg_537 <= trunc_ln186_fu_415_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_phi_ln224_1_phi_fu_257_p4 = tm;
    end else begin
        ap_phi_mux_phi_ln224_1_phi_fu_257_p4 = phi_ln224_1_reg_254;
    end
end

always @ (*) begin
    if (((enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_phi_ln224_phi_fu_248_p4 = tr;
    end else begin
        ap_phi_mux_phi_ln224_phi_fu_248_p4 = phi_ln224_reg_245;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_return_0 = ap_phi_mux_phi_ln224_1_phi_fu_257_p4;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_return_1 = ap_phi_mux_phi_ln224_phi_fu_248_p4;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_buf_address0 = zext_ln219_fu_446_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        local_buf_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_address0;
    end else begin
        local_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_buf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        local_buf_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_ce0;
    end else begin
        local_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_buf_d0 = or1_fu_437_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        local_buf_d0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_d0;
    end else begin
        local_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln217_fu_431_p2 == 1'd0) & (enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        local_buf_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        local_buf_we0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_local_buf_we0;
    end else begin
        local_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (enable_read_read_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((ap_start == 1'b1) & (enable_read_read_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Input_0_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_0_address0;

assign Input_0_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_0_ce0;

assign Input_10_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_10_address0;

assign Input_10_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_10_ce0;

assign Input_11_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_11_address0;

assign Input_11_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_11_ce0;

assign Input_12_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_12_address0;

assign Input_12_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_12_ce0;

assign Input_13_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_13_address0;

assign Input_13_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_13_ce0;

assign Input_14_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_14_address0;

assign Input_14_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_14_ce0;

assign Input_15_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_15_address0;

assign Input_15_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_15_ce0;

assign Input_16_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_16_address0;

assign Input_16_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_16_ce0;

assign Input_17_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_17_address0;

assign Input_17_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_17_ce0;

assign Input_18_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_18_address0;

assign Input_18_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_18_ce0;

assign Input_19_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_19_address0;

assign Input_19_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_19_ce0;

assign Input_1_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_1_address0;

assign Input_1_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_1_ce0;

assign Input_20_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_20_address0;

assign Input_20_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_20_ce0;

assign Input_21_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_21_address0;

assign Input_21_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_21_ce0;

assign Input_22_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_22_address0;

assign Input_22_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_22_ce0;

assign Input_23_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_23_address0;

assign Input_23_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_23_ce0;

assign Input_24_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_24_address0;

assign Input_24_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_24_ce0;

assign Input_25_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_25_address0;

assign Input_25_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_25_ce0;

assign Input_26_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_26_address0;

assign Input_26_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_26_ce0;

assign Input_27_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_27_address0;

assign Input_27_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_27_ce0;

assign Input_28_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_28_address0;

assign Input_28_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_28_ce0;

assign Input_29_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_29_address0;

assign Input_29_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_29_ce0;

assign Input_2_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_2_address0;

assign Input_2_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_2_ce0;

assign Input_30_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_30_address0;

assign Input_30_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_30_ce0;

assign Input_31_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_31_address0;

assign Input_31_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_31_ce0;

assign Input_32_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_32_address0;

assign Input_32_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_32_ce0;

assign Input_33_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_33_address0;

assign Input_33_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_33_ce0;

assign Input_34_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_34_address0;

assign Input_34_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_34_ce0;

assign Input_35_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_35_address0;

assign Input_35_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_35_ce0;

assign Input_36_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_36_address0;

assign Input_36_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_36_ce0;

assign Input_37_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_37_address0;

assign Input_37_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_37_ce0;

assign Input_38_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_38_address0;

assign Input_38_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_38_ce0;

assign Input_39_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_39_address0;

assign Input_39_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_39_ce0;

assign Input_3_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_3_address0;

assign Input_3_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_3_ce0;

assign Input_40_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_40_address0;

assign Input_40_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_40_ce0;

assign Input_41_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_41_address0;

assign Input_41_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_41_ce0;

assign Input_42_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_42_address0;

assign Input_42_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_42_ce0;

assign Input_43_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_43_address0;

assign Input_43_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_43_ce0;

assign Input_44_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_44_address0;

assign Input_44_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_44_ce0;

assign Input_45_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_45_address0;

assign Input_45_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_45_ce0;

assign Input_46_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_46_address0;

assign Input_46_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_46_ce0;

assign Input_47_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_47_address0;

assign Input_47_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_47_ce0;

assign Input_48_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_48_address0;

assign Input_48_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_48_ce0;

assign Input_49_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_49_address0;

assign Input_49_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_49_ce0;

assign Input_4_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_4_address0;

assign Input_4_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_4_ce0;

assign Input_50_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_50_address0;

assign Input_50_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_50_ce0;

assign Input_51_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_51_address0;

assign Input_51_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_51_ce0;

assign Input_52_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_52_address0;

assign Input_52_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_52_ce0;

assign Input_53_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_53_address0;

assign Input_53_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_53_ce0;

assign Input_54_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_54_address0;

assign Input_54_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_54_ce0;

assign Input_55_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_55_address0;

assign Input_55_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_55_ce0;

assign Input_56_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_56_address0;

assign Input_56_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_56_ce0;

assign Input_57_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_57_address0;

assign Input_57_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_57_ce0;

assign Input_58_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_58_address0;

assign Input_58_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_58_ce0;

assign Input_59_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_59_address0;

assign Input_59_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_59_ce0;

assign Input_5_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_5_address0;

assign Input_5_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_5_ce0;

assign Input_6_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_6_address0;

assign Input_6_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_6_ce0;

assign Input_7_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_7_address0;

assign Input_7_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_7_ce0;

assign Input_8_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_8_address0;

assign Input_8_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_8_ce0;

assign Input_9_address0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_9_address0;

assign Input_9_ce0 = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_Input_9_ce0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign cmp15_fu_409_p2 = ((ltype == 8'd0) ? 1'b1 : 1'b0);

assign enable_read_read_fu_190_p2 = enable;

assign grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_IsNL = IsNL;

assign grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start = grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_ap_start_reg;

assign icmp_ln217_fu_431_p2 = ((grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_bn_local_out == 4'd0) ? 1'b1 : 1'b0);

assign mul_ln186_fu_403_p0 = mul_ln186_fu_403_p00;

assign mul_ln186_fu_403_p00 = tr;

assign mul_ln186_fu_403_p1 = 10'd26;

assign or1_fu_437_p3 = {{grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_1_0121_out}, {grp_nonlinear_leaky_row_Pipeline_VITIS_LOOP_182_1_fu_263_buf_256b_0_0120_out}};

assign trunc_ln186_fu_415_p1 = tm[5:0];

assign zext_ln219_fu_446_p1 = cnt_loc_fu_162;

endmodule //FPGA_Acc_nonlinear_leaky_row
